import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

import { SessionProvider } from "next-auth/react";

import { auth } from "@/auth";
import { cn } from "@/lib/utils";

import { QueryProvider } from "@/components/providers/query-provider";

const font = Inter({
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jotion",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={cn(geistMono.variable, font.className, "antialiased")}>
          <QueryProvider>
            {children}
          </QueryProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
